[default]
value = "value for default"

[development]
value = "value for development"

[staging]
value = "value for staging"

[testing]
value = "value for testing"

[production]
value = "value for production"

[global]

MONGO_HOST = "localhost"
MONGO_PORT = 19823

STATIC_FOLDER = 'static'